networks:
  postgres:
    driver: bridge


services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: flutterjunction
      POSTGRES_PASSWORD: flutterjunction
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pdadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
